[package]
name = "foundry"
version = "0.1.0"
edition = "2024"

[dependencies]
nix = { version = "0.30.1", features = ["sched", "signal", "mount", "dir"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
